### ISSUE TITLE
Output without [stdout]

### ISSUE THREAD

**Issue by groob** [dfinninger/lita-cmd#1]
Hi is it possible to display cmd output without [stdout]/[stderr] ?

**Comment by DannyBen** [comment]
I am also in favor of allowing some config for it. Also the three ticks wrapping the output are simply visible as is when used in HipChat - so I would be happy to see config for disabling that as well.

**Comment by dfinninger** [comment]
Hello, @groob and @DannyBen sorry I've been away from Github for so long! Looking into this now.

**Comment by dfinninger** [comment]
Fixed in #5
