### ISSUE TITLE
Tilde files ...

### ISSUE THREAD

**Issue by henrikjohansen** [dfinninger/lita-cmd#15]
I would be awesome if this plugin could automagically remove tilde files (my_script~) from the cmd list output ... same goes for files starting and ending with # (all generated by various editors).

**Comment by dfinninger** [comment]
Just seeing this. Got back from my first vacation in a while :)

So are you talking about the temp files created by Emacs/Vim/etc?
Or are you asking for a mechanism to "hide" files?
Or is it something else?

**Comment by henrikjohansen** [comment]
What I a asking for is a way to hide those files, yes.

**Comment by dfinninger** [comment]
Added in #19
