### ISSUE TITLE
no gem path for ruby cmds

### ISSUE THREAD

**Issue by bmcgair** [dfinninger/lita-cmd#20]
bash based commands seem to work fine, but I have a few ruby based scripts that work from a shell prompt, but can't find required gems when executed through lita-cmd. It's like they have no gem path.

I'm struggling to understand exactly what sort of env is inherited by lita-cmd.

**Comment by VAdamec** [comment]
You can use bash script envelop, to at least dump environment setup. Maybe using RVM will be an option.

**Comment by bmcgair** [comment]
I don't quite see how a shell script wrapper is going to work with cmdline options. Seems like a lot more work than doing my own lita handler to handle my commands.

Damn. I was hoping I could just port all of my existing stuff by linking existing scripts to the cmds dir. What other interpreters don't work?

**Comment by VAdamec** [comment]
Something like this ? just to see what environment and vars are setup/used by Lita during command launch.

mytest
```bash
#!/bin/bash -x
export
gem env
/bin/ruby myscript.rb
```

**Comment by VAdamec** [comment]
On my installation I with shell envelop no problem to run anything.

test
```
#!/bin/bash
gem env
/usr/bin/ruby /opt/lita/lab/myscript.rb
```

myscript.rb
```
require 'rubygems'
puts 'Hello, world!'
```

Result when called via Hipchat (run lab/test)
```
RubyGems Environment:
  - RUBYGEMS VERSION: 
....
  - GEM PATHS:
     - /usr/local/share/gems
     - /opt/lita/.gem/ruby
     - /usr/share/gems
.....
Hello, world!
```

**Comment by bmcgair** [comment]
Your test works for me, but if I require another gem that I've installed locally it's still not found.
gem install aws-sdk

foo.rb:
require 'rubygems'
require 'aws-sdk'
puts 'Hello, world!'

/home/ubuntu/botcmds/foo:2:in require': cannot load such file -- aws-sdk (LoadError) from /home/ubuntu/botcmds/foo:2:in

'
Again, same script works from a shell prompt, so there's something missing in the ruby env in lita-cmd? Or maybe its using a different ver of ruby somehow, though I can't quite figure out where that would come from. I'm actually sort of baffled. Out of ideas.

If lita-cmd only works with shell scripts I wish I would have known that up front. Maybe you should rename this module lita-bash.

**Comment by bmcgair** [comment]
The problem seems to be that I have no gem env. So if I create a cmd:

#!/bin/bash -x
gem env

/home/ubuntu/.rbenv/shims/ruby ~/botcmds/helloworld

I have no gem env

**Comment by bmcgair** [comment]
this is fucking hopeless

**Comment by bmcgair** [comment]
OK solved. I have to include my missing gems in the Gemfile for the bot itself, then rebundle. 
Dunno why this conceptually was so difficult for me to figure out. I kept thinking of the drop in ruby commands as standalone, not within the context of lita.
