### ISSUE TITLE
Ability to customize the "cmd" prefix

### ISSUE THREAD

**Issue by DannyBen** [dfinninger/lita-cmd#6]
Hey,

I wanted to create a more friendly bot interaction, and say things like `bot list` (to show list of actions) or `bot scriptname` to run the script, or maybe - in cases where the bot has other plugins - to at least have a more fluent sentence when talking to the bot, like `bot run list` and `bot run myscript`

I have committed a version that supports customizing the `cmd` prefix by config, if you are interested, I can create a PR.

[Option 1](https://github.com/dfinninger/lita-cmd/compare/master...DannyBen:simplified-interaction?expand=1) - the simplified-interaction branch with this feature, as created on top of your master
[Option 2](https://github.com/dfinninger/lita-cmd/compare/master...DannyBen:dev?expand=1) - a merged branch of both this feature and my previous PR #5

**Comment by dfinninger** [comment]
Command structure is a little wonky. I was just getting something on the table when I was writing this. I agree about cleaning up the interface a bit.

I'm partial to `bot list` and `bot run SCRIPT`.

**Comment by dfinninger** [comment]
Closed due to #9
